### ISSUE TITLE
Rate limiting for parrallelisation

### ISSUE THREAD

**Issue by leclem** [Vikit-ai/sdk#103]
Some model backends do not accept more than x videos per second, so it would be helpful in the long run to have a rate limiting implemented.
Also, when launching parallel tasks, it would be helpful to be able to wait something from 1 to 10 seconds before launching each of the individual tasks, as some rate limiters also block model launch when too much parallel calls are made exactly at the same time.

**Comment by jeffmac-aix** [comment]
Batch of videos used as a first rate limiting strategy (i.e. 15 vids to be used at the same time before the next 15 ones) though it brings the open issue of overall max limits on the provider platform.
TOday strategy is to say that if we need more QPS on provider they will raise the roof as being heavier consumers of their service, still a prioritized queue system will be implemented on cloud api's to handle multiple provider limitations for the long run. 
Closing this one and opening a new feature request for cloud API parralelisation V2
