### ISSUE TITLE
Retry if URL sent is null

### ISSUE THREAD

**Issue by leclem** [Vikit-ai/sdk#39]
In some cases, when replicate is failing, it sends a "null" url instead of failing the http request. Maybe we should just test that the url is correct and if not relaunch a replicate / backend job ? It happens often for amt.

This gives an error :  

ValueError                                Traceback (most recent call last)

[<ipython-input-14-3a213a9aeb66>](https://localhost:8080/) in <cell line: 20>()

     21     vid_cp_sub = CompositeVideo()

     22

---> 23     keyword_based_vid = RawTextBasedVideo(sub.text).build(

     24         build_settings=VideoBuildSettings(

     25             generate_from_llm_keyword=True,

 

7 frames

[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/) in _parse(self)

    375         self.type, rest = _splittype(self._full_url)

    376         if self.type is None:

--> 377             raise ValueError("unknown url type: %r" % self.full_url)

    378         self.host, self.selector = _splithost(rest)

    379         if self.host:

 

ValueError: unknown url type: ''

**Comment by jeffmac-aix** [comment]
this will be addressed trough different complementary ways:
1) simple retry logic, as a quick fix
2) possibly even before 1. , restarting the whole video production process where it where thanks to checkpoints. As expected on https://github.com/Vikit-ai/sdk/issues/130
3) just use hooks, now that we are extending our vikit.ai Cloud API's

**Comment by jeffmac-aix** [comment]
resolved in VikitGateway with if not response.startswith("http"):
                        raise AttributeError("The result audio link is not a link")

**Comment by jeffmac-aix** [comment]
The resolution stops the whole video process, feature https://github.com/Vikit-ai/sdk/issues/130 shall alleviate this problem and allow to restart the process where it where cancelled

**Comment by jeffmac-aix** [comment]
resolved with. https://github.com/Vikit-ai/sdk/commit/32b4926203333e81a089c563b610af52770a1704
