### ISSUE TITLE
PromptFactory() get full text gives wrong out put (not urgent)

### ISSUE THREAD

**Issue by leclem** [Vikit-ai/sdk#60]
When I create a prompt from text, get_full_text function does not give the correct value! I should use .text instead. Is it normal?

```python
async def batch_raw_text_based_prompting(
    prompt_file: str, model_provider: str = "videocrafter"
):
    to_interpolate = False
    # True if model_provider == "videocrafter" else False

    prompt_df = pd.read_csv(prompt_file, delimiter=";", header=0)
    for _, row in prompt_df.iterrows():
        output_file = f"{row.iloc[0]}.mp4"
        prompt = await PromptFactory().create_prompt_from_text(row.iloc[1])
        video_build_settings = VideoBuildSettings(
            music_building_context=MusicBuildingContext(
                apply_background_music=True, generate_background_music=True
            ),
            test_mode=False,
            interpolate=to_interpolate,
            target_model_provider=model_provider,
            output_video_file_name=output_file,
        )
        video_build_settings.prompt = prompt
        video = RawTextBasedVideo(prompt.get_full_text())
        await video.build(build_settings=video_build_settings)

```

so if I run  with ```row.iloc[0]= "The remnants of humanity struggle to survive in a world overrun by relentless, mechanical sentinels"```
```prompt.get_full_text()``` will give me: 

```A group of ancient moss-covered stones come to life in an abandoned forest, revealing intricate carvings and symbols. A young boy traveling in the train alongside Mediterranean coast, contemplating the sea and loving it. A group of ancient moss-covered stones come to life in an abandoned forest, revealing intricate carvings and symbols. A young boy traveling in the train alongside Mediterranean coast, contemplating the sea and loving it. A group of ancient moss-covered stones come to life in an abandoned forest, revealing intricate carvings and symbols. A young boy traveling in the train alongside Mediterranean coast, contemplating the sea and loving it. A group of ancient moss-covered stones come to life in an abandoned forest, revealing intricate carvings and symbols. A young boy traveling in the train alongside Mediterranean coast, contemplating the sea and loving it.```

**Comment by jeffmac-aix** [comment]
At first sight, I would say that the issue comes from         prompt = await PromptFactory().create_prompt_from_text(row.iloc[1])
where the testmode is not passed to the PromptFactory constructor. 

I see from the latest code base on main branch and batch_raw_text_based_prompting  function that someone seems to have fixed this using the following code, can you confirm it is resolved?

  video_build_settings.prompt = await PromptFactory(
            ml_gateway=video_build_settings.get_ml_models_gateway()
        ).create_prompt_from_text(prompt_content)

**Comment by leclem** [comment]
Yes, it is fixed by explicitly passing the right ml gateway using the buildsettings. I close the issue.
