### ISSUE TITLE
Composite video cannot have read aloud prompt

### ISSUE THREAD

**Issue by leclem** [Vikit-ai/sdk#79]
A composite video with these build settings : 
video_build_settings = VideoBuildSettings(
        music_building_context=MusicBuildingContext(
            apply_background_music=True,
            generate_background_music=True,
        ),
        test_mode=False,
        include_read_aloud_prompt=True,
        target_model_provider="videocrafter",
        output_video_file_name="Coffee.mp4",
        interpolate=True,
    )

Do not have a read aloud prompt even if we set-it up. Example in the example colab

**Comment by jeffmac-aix** [comment]
not reproduced on similar integration test : test_build_tom_cruse_video from TestPromptBasedVideo
Looking the collab, which one please?

**Comment by jeffmac-aix** [comment]
Looking at the latest collab, we do have a read aloud prompt, don't we? \fyi In the way of checking this, I found and fixed another  bug to prepare build_settings for PromptBasedVideo, so the error message on the log re coroutine will be gone

**Comment by leclem** [comment]
Oh I see we need to specify the prompt from promptFactory in video_build_settings
