### ISSUE TITLE
Show a nice warning message to explain we need a vikit key

### ISSUE THREAD

**Issue by jeffmac-aix** [Vikit-ai/sdk#87]
Today an error is raised when vikit key is missing, let's show something funnier to push developers get their key with hyperlink to the subscription link
Today we lose too many testers because of this

**Comment by jeffmac-aix** [comment]
Also let the user knoz she needs to restart the colab after using the key

**Comment by jeffmac-aix** [comment]
Yes that looks like a great message for now, thanks!
So if you want I can assign you to this issue?

On the related note, you are right the none checks are useless and not the intended behavior.  Feel free to include a fix on the same pull request or another one, as you wish as those are mostly environment matters

**Comment by prithiv256** [comment]
Yeah, I'd appreciate it if you could assign this to me. I'll send a pull request soon

**Comment by jeffmac-aix** [comment]
solved with fr #108
